export function render() {
    return `
    <div id='home' data-server-rendered="true">
        <h3>Home Page</h3>
        <p><a href="/list">list link</a>&nbsp;&nbsp;<a href="/detail">detail link</a></p>
        <input type="text" value="Hello"><br>
        <input type="text" value="World !">
        <ul style="padding:15px">
            <li>Hello</li>
            <li>World !</li>
        </ul>
        <p>Hello World !</p>
        <div><p>I am generated by<strong style="color: red">&nbsp;v-html</strong></p></div>
        <button>change model</button>
    </div>`;
}
